# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
executors:
  node-executor:
    docker:
      - image: cimg/node:16.10.0

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: "Test target availability"
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_HOST 'echo test';
      - run: 
          name: "Install dependencies"
          command: |
            npm i;
      - run: 
          name: "Build app"
          command: |
            npm run build;
      - run: 
          name: "Deploy"
          command: |
            chmod +x ./install.sh;
            scp -o StrictHostKeyChecking=no fe-build.zip $SSH_HOST:fe-build.zip;
            scp -o StrictHostKeyChecking=no install.sh $SSH_HOST:install.sh;
            ssh -o StrictHostKeyChecking=no $SSH_HOST './install.sh';


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  front-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
